version: '3'

services:
  web :
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    
  db:
    image: postgres
    environment:
      POSTGRES_DB: expense_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8954
      
  