version: '3'

services:
  web :
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    
  db:
    image: postgres
    environment:
      POSTGRES_DB: expense_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8954
      
#   version: '19.03.13'
# services:
#   web:
#     build: .
#     command: flask run --host=0.0.0.0
#     volumes:
#       - .:/code
#     ports:
#       - "5000:5000"
#     environment:
#       - FLASK_ENV=development
#     depends_on:
#       - db
#   db:
#     image: postgres:latest
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_DB=expense_tracker_db

# volumes:
#   postgres_data:
